// src/components/botao-rolagem/botao-rolagem.tsx
import styles from "./botao-rolagem.module.scss"

function BotaoRolagem({valor} : {valor:number}){


    return(
        <button className={styles.rollBtn}>
            <img src={"/icons/dados/d20.svg"} alt="Rolagem" />
            <p>{valor}</p>
        </button>
    )
}

export default BotaoRolagem

// src/app/shared/components/botao-rolagem/botao-rolagem.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-botao-rolagem',
  imports: [],
  templateUrl: './botao-rolagem.component.html',
  styleUrl: './botao-rolagem.component.scss'
})
export class BotaoRolagemComponent {

  @Input() valor!: number
}

<button class="rolagem">
    <img src="/d20.svg" alt="rolagem">
    <p>{{valor}}</p>
</button>
