// src/components/barra-recurso/barra-recurso.tsx
import { useEffect, useState } from "react"
import styles from "./barra-recurso.module.scss"

function BarraRecurso({
    css,
    atual,
    maximo
}: {
    css: string,
    atual: number,
    maximo: number
}) {

    const [larguraBarra, setLarguraBarra] = useState(0)

    useEffect(() => {
        setLarguraBarra((atual / maximo) * 100)
    }, [atual, maximo])

    return (
        <div className={styles.barraRecurso}>
            <div className={`${styles[css]} ${styles.barra}`} style={{ width: `${larguraBarra}%` }}></div>
            <div className={styles.texto}>
                <p>{atual + "/" + maximo}</p>
            </div>
        </div>
    )
}

export default BarraRecurso

// src/app/pages/ficha-personagem/components/barra-recurso/barra-recurso.component.ts
import { Component, Input, OnChanges, SimpleChanges } from '@angular/core';

@Component({
  selector: 'app-barra-recurso',
  imports: [],
  templateUrl: './barra-recurso.component.html',
  styleUrl: './barra-recurso.component.scss'
})
export class BarraRecursoComponent implements OnChanges {

  @Input() atual: number = 0
  @Input() maximo: number = 0
  @Input() css: string = ""

  larguraBarra:number = 0

  ngOnInit() {
    this.larguraBarra = (this.atual / this.maximo) * 100
  }

  ngOnChanges(changes : SimpleChanges){
    this.larguraBarra = (this.atual / this.maximo ) * 100
  }
}

<div class="barraRecurso">
    <div class="{{'barra ' + css}}" [style]="{'width' : larguraBarra+'%'}"></div>
    <div class="texto">
        <p>{{atual + "/" + maximo}}</p>
    </div>
</div>
