// src/app/shared/components/botao-modular/botao-modular.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-botao-modular',
  imports: [],
  templateUrl: './botao-modular.component.html',
  styleUrl: './botao-modular.component.scss'
})
export class BotaoModularComponent {

  @Input() css!: string
  @Input() icone!: string
  @Input() texto!: string
}

<button class="{{css}}">
    @if(icone){
    <img src="{{'/' + icone }}" alt="{{texto}}">
    }
    <p>{{texto}}</p>
</button>

// src/components/botao-modular/botao-modular.tsx
import styles from "./botao-modular.module.scss"

function BotaoModular({
    icone,
    css,
    texto
}: {
    icone?: string,
    css: string,
    texto?: string | number
}) {

    return (
        <button className={styles[css]}>
            {
                icone &&
                <img className={styles.icone} src={icone} alt={String(texto)} />
            }
            {
                texto &&
                <p>{texto}</p>
            }
        </button>
    )
}

export default BotaoModular
